// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/agents" | "/avatars" | "/avatars/[slug]" | "/big-swings" | "/broll" | "/knowledge" | "/login" | "/pipeline" | "/pipeline/[id]" | "/products" | "/research" | "/research/[id]" | "/reviews" | "/runs" | "/runs/[id]" | "/scripts" | "/scripts/[id]" | "/scripts/new" | "/settings" | "/spy" | "/usage" | "/verbatims" | "/winners"
type AppRouteHandlerRoutes = "/api/broll-thumb/[driveId]" | "/api/debug-env"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/agents": {}
  "/api/broll-thumb/[driveId]": { "driveId": string; }
  "/api/debug-env": {}
  "/avatars": {}
  "/avatars/[slug]": { "slug": string; }
  "/big-swings": {}
  "/broll": {}
  "/knowledge": {}
  "/login": {}
  "/pipeline": {}
  "/pipeline/[id]": { "id": string; }
  "/products": {}
  "/research": {}
  "/research/[id]": { "id": string; }
  "/reviews": {}
  "/runs": {}
  "/runs/[id]": { "id": string; }
  "/scripts": {}
  "/scripts/[id]": { "id": string; }
  "/scripts/new": {}
  "/settings": {}
  "/spy": {}
  "/usage": {}
  "/verbatims": {}
  "/winners": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
