// The Avatar Deep Dive template — the canonical quality bar + section spec for
// sub-avatar research. Distilled from a hand-authored 90-page gold-standard deep
// dive (the "Avatar Post Partum" exemplar). This is what `researchSubAvatars`
// aims to produce: not 8 flat fields, but a structured, evidence-tiered profile
// rich enough for the strategist/copywriter/designer to write converting scripts.
//
// Seeded as a `deep_dive_template` SOP (roleScope: researcher) so it lives in
// /knowledge and is editable at runtime. research.ts loads it from the DB and
// falls back to this constant when the DB isn't seeded yet.

export const DEEP_DIVE_TEMPLATE_TITLE = "Avatar Deep Dive — section spec & quality bar";

export const DEEP_DIVE_TEMPLATE = [
  "You are producing an AVATAR DEEP DIVE — the richest possible profile of ONE sub-avatar,",
  "built entirely from how REAL PEOPLE talk about this problem in their own words.",
  "This is not a summary. It is the source material a copywriter, strategist, and designer",
  "will mine to write ads that make the reader feel SEEN. Depth and specificity win.",
  "",
  "════════════════════════════════════════════════════════════════════════",
  "EVIDENCE TIERING — label every quote",
  "════════════════════════════════════════════════════════════════════════",
  "  • verbatim      = a real phrase you actually read in a source (quote it close to exact).",
  "  • reconstructed = a phrase you synthesized from a clear PATTERN across multiple sources",
  "                    (not invented — it must be the natural distillation of what you saw).",
  "Prefer verbatim. Reconstructed is allowed only when the pattern is unmistakable.",
  "Cite the source (subreddit, forum, Quora, review) for verbatim items wherever possible.",
  "",
  "════════════════════════════════════════════════════════════════════════",
  "SECTIONS — fill every one with specificity, not generic marketing language",
  "════════════════════════════════════════════════════════════════════════",
  "",
  "1. VOICE PROFILE — how she actually writes/talks.",
  "   register (e.g. 'late-night voice memo to a close friend'), humorStyle, cursingLevel,",
  "   emotionalTone (e.g. 'guilty-but-determined'), formalityLevel (1-5).",
  "",
  "2. VOCABULARY CONSTRAINTS",
  "   powerWords[]      — the loaded words she reaches for (e.g. 'me', 'before', 'miss', 'stayed').",
  "   phrasesToUse[]    — exact phrases that land ('I miss me', 'I should be grateful, but').",
  "   forbiddenWords[]  — marketing clichés her BS detector rejects ('bounce back', 'snap back',",
  "                       'get your body back', 'transformation', 'empower', 'journey', 'snatched').",
  "                       These are RESONANCE blocks, distinct from legal/compliance blocks.",
  "   registerRules[]   — how she constructs language (flat declaratives, ellipsis on the hardest",
  "                       feeling, ALL-CAPS on the one weight-bearing word, self-corrects in real time).",
  "",
  "3. SENTENCE PATTERNS",
  "   structures[]      — her go-to constructions (e.g. 'I used to [X]. Now I [Y].').",
  "   typicalLength, punctuationHabits, fragmentsVsComplete.",
  "",
  "4. EMOTIONAL REGISTER — peak (the acute spike + its trigger), baseline (the steady state),",
  "   suppressed (what she feels but won't say aloud). Name the PRIMARY emotion (e.g. 'identity grief').",
  "",
  "5. METAPHORS SHE USES — the mental images she reaches for (e.g. 'the closet as a museum of",
  "   her former self', 'photos as grief ambushes'), each with WHY it resonates.",
  "",
  "6. BRIDGE TO MECHANISM",
  "   beliefGaps      — what she wrongly believes about the problem (e.g. 'effort is the only lever').",
  "   howSheTalksAboutCause — her own (often non-physiological) mental model.",
  "   hookBridge      — the one or two sentences that move her from her false belief to the product's",
  "                     real mechanism, in her language. Leave a [PRODUCT MECHANISM NAME] placeholder.",
  "",
  "7. DEEP DESIRES (rank them) — for each: surface (what she'd say she wants), middle, core (the real",
  "   driver), the massInstinct it ladders to (HEALTH/SURVIVAL, STATUS, SEX/RELATIONSHIPS, COMFORT,",
  "   CONTROL, BELONGING), a connectionChain (product feature → benefit → her words → instinct), and a",
  "   copyAngle. Rank by a Desire Power score: scope (how widely shared, 1-10) × urgency × stayingPower.",
  "",
  "8. BIG 4 EMOTIONS — for each of Big-Fast, New-Only, Easy-Anybody, Safe-Predictable: is it applicable,",
  "   and the angle that activates it. Identify which is STRONGEST for this avatar.",
  "",
  "9. ANGLE CANDIDATES (3-5, ranked) — each scored Ev (emotional voltage), Ma (mass-instinct match),",
  "   Ws (winning-signal / how filmable+specific), with a total. For each: name, exampleHook (in her",
  "   voice), reasonToBuy, emotionalLever, and 2-3 conceptDirections (concrete ad treatments).",
  "",
  "10. CUSTOMER LANGUAGE MINING — grouped buckets of real phrases, each tier-labeled with evidence:",
  "    pain[], desire[], identity[], actionCoping[], bodySensation[], emotionalState[], failedSolution[].",
  "    This is the verbatim well the copywriter draws hooks from. Quantity + fidelity matter here.",
  "",
  "11. TRUST & PROOF",
  "    trustSignals[]      — what makes her believe (e.g. 'a real mom at Target, not a photoshoot';",
  "                          'reviews from women who look like me'; size-inclusive proof; a guarantee).",
  "    skepticismObjections[] — the rational walls ('how does a legging fix what 9 months did?').",
  "    failedSolutions[]   — what she's already tried and why it failed (sets the differentiation bar).",
  "",
  "12. TRIGGERS & CALENDAR",
  "    triggerMoments[]    — the concrete events that convert passive grief into active buying",
  "                          (return-to-work, date night, family photos, 'On This Day' photo ambush).",
  "    desireCalendar      — peakMonths[] and a seasonalAngle for each (Jan resolutions, summer exposure…).",
  "",
  "13. IDENTIFICATION MARKETING — selfImageToPortray, whereTheyWantToBe, whatTheyWantToFeel,",
  "    whatTheyWantToLookLike (in her terms, e.g. 'not a hot mom — HERSELF').",
  "",
  "14. BUYER PSYCHOLOGY",
  "    buyerVsUser         — are they the same person? where/when does the purchase happen?",
  "    buyingEmotions      — score 0-10 each: fear, guilt, pride, shame, trust, excitement, with evidence.",
  "                          (Trust is usually LOW; guilt/shame are often the sleeper blockers.)",
  "    painDesireRatio     — pain% vs desire% + the copy implication (e.g. 'open with the wound,",
  "                          pivot to the reunion within 3-5 seconds — don't make her wallow').",
  "    purchaseHesitation  — the top blocker (often a compound lock, e.g. skepticism + guilt).",
  "    counterStrategy     — the exact order to dissolve those locks (e.g. break guilt first via reframe,",
  "                          then skepticism via immediacy proof + guarantee).",
  "",
  "════════════════════════════════════════════════════════════════════════",
  "QUALITY BAR — abridged exemplar (the 'Avatar Post Partum' gold standard)",
  "════════════════════════════════════════════════════════════════════════",
  "This is the depth and tone to match. Yours must be just as specific and just as grounded.",
  "",
  "  • PRIMARY EMOTION: identity grief — 'mourning a self she can still remember but can no longer see.'",
  "  • CORE DESIRE (core, not surface): 'so I can stop grieving the woman I used to be and feel like I",
  "    still exist inside this new body.' Surface = 'I want my pre-pregnancy legs back.'",
  "  • VERBATIM POWER PHRASES: 'I miss me.' · 'I have eyes. I KNOW what I looked like before.' ·",
  "    'it just… stayed.' · 'I feel like I traded my body for my baby.' (sources: r/beyondthebump,",
  "    r/Mommit, r/postpartumprogress).",
  "  • FORBIDDEN (resonance blocks): 'bounce back', 'snap back', 'get your body back', 'transformation',",
  "    'mama bear', 'self-care isn't selfish' — using these triggers rejection.",
  "  • BUYER PSYCHOLOGY: Guilt 9, Shame 8, Fear 8, Trust 4. → Counter: dissolve guilt first",
  "    ('you gave your body for 9 months; this is 30 seconds of giving it back to yourself'), THEN prove",
  "    with immediacy + guarantee. Pain/Desire 60/40: open with the mirror/photo/closet wound, close",
  "    with the reunion fast.",
  "  • TOP ANGLE (Ev10/Ma9/Ws9): 'The Mirror Reunion' — hook: 'I put them on and just… stood there.",
  "    Because for the first time in 14 months, I saw her. I saw me.' Concept: camera on her FACE, not",
  "    her body — the shift from bracing to recognition.",
  "",
  "Match this. Ground every claim in patterns across multiple real-people sources. Specificity is the product.",
].join("\n");
